### ISSUE TITLE
[bug] https://digiwf.muenchendigital.io/ is broken

### ISSUE THREAD

**Issue by xdoo** [it-at-m/digiwf-project#234]
**Describe the bug**
[The Landing Page](https://digiwf.muenchendigital.io/) is broken (404).
![image](https://user-images.githubusercontent.com/712911/171697713-e9ac6168-386c-4b30-b4f8-7a76db2e4064.png)

The problem is, that index.html in `branch gh-pages` is missing:

![image](https://user-images.githubusercontent.com/712911/171697853-7aef50da-a8f5-4011-8763-921d80c9fa64.png)

The workflow (workflows/cd.yml) calls `yarn generate`:

![image](https://user-images.githubusercontent.com/712911/171697960-c0d23f86-4fe4-495c-9a47-75d6435e97f8.png)

 I can't reproduce this on my local machine. If I check out main an run `yarn generate`, an `index.html ` is in `dist`.

**To Reproduce**
Call [the Landing Page](https://digiwf.muenchendigital.io/) 

**Expected behavior**
I want to see this:

![image](https://user-images.githubusercontent.com/712911/171698390-7018f75b-636f-412e-bc61-ba86ab608e54.png)

**Screenshots**

**Comment by lmoesle** [comment]
The upgrade from version 1 to 2 of `@nuxt/content` did not go well. It seems that the api changed and we have to refactor our code.
As a temporary solution I prepared a downgrade of `@nuxt/content`s  version https://github.com/it-at-m/digiwf-project/pull/235 

I get the following error:

```
ℹ Full static generation activated                                                                                                                                                                         20:41:53
ℹ Generating output directory: dist/                                                                                                                                                                       20:41:53
ℹ Generating pages with full static mode                                                                                                                                                                   20:41:53

 ERROR   /de                                                                                                                                                                                               20:41:54

TypeError: $content is not a function
    at asyncData (pages/index.vue:89:0)
    at promisify (node_modules/.cache/nuxt/utils.js:304:0)
    at server.js:15143:23
    at Array.map (<anonymous>)
    at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:231:0)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)


 ERROR  $content is not a function                                                                                                                                                                         20:41:54

  at asyncData (pages/index.vue:89:0)
  at promisify (node_modules/.cache/nuxt/utils.js:304:0)
  at server.js:15143:23
  at Array.map (<anonymous>)
  at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:231:0)
  at runNextTicks (node:internal/process/task_queues:61:5)
  at listOnTimeout (node:internal/timers:528:9)
  at processTimers (node:internal/timers:502:7)


 ERROR   /                                                                                                                                                                                                 20:41:54

TypeError: $content is not a function
    at asyncData (pages/index.vue:89:0)
    at promisify (node_modules/.cache/nuxt/utils.js:304:0)
    at server.js:15143:23
    at Array.map (<anonymous>)
    at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:231:0)


 ERROR  $content is not a function                                                                                                                                                                         20:41:54

  at asyncData (pages/index.vue:89:0)
  at promisify (node_modules/.cache/nuxt/utils.js:304:0)
  at server.js:15143:23
  at Array.map (<anonymous>)
  at module.exports.__webpack_exports__.default (node_modules/.cache/nuxt/server.js:231:0)
```
